# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id:  ID, size: SIZE, name:  NAME},
#     ...
#   ]
standalone_tags:
  [
    
{id: 101 ,size: 0.20, name: "101 "},
{id: 102 ,size: 0.20, name: "102 "},
{id: 103 ,size: 0.20, name: "103 "},
{id: 104 ,size: 0.20, name: "104 "},
{id: 105 ,size: 0.20, name: "105 "},
{id: 106 ,size: 0.20, name: "106 "},
{id: 107 ,size: 0.20, name: "107 "},
{id: 108 ,size: 0.20, name: "108 "},
{id: 109 ,size: 0.20, name: "109 "},
{id: 110 ,size: 0.20, name: "110 "},
{id: 111 ,size: 0.20, name: "111 "},
{id: 112 ,size: 0.20, name: "112 "},
{id: 113 ,size: 0.20, name: "113 "},
{id: 114 ,size: 0.20, name: "114 "},
{id: 115 ,size: 0.20, name: "115 "},
{id: 116 ,size: 0.20, name: "116 "},
{id: 117 ,size: 0.20, name: "117 "},
{id: 118 ,size: 0.20, name: "118 "},
{id: 119 ,size: 0.20, name: "119 "},
{id: 120 ,size: 0.20, name: "120 "},
{id: 121 ,size: 0.20, name: "121 "},
{id: 122 ,size: 0.20, name: "122 "},
{id: 123 ,size: 0.20, name: "123 "},
{id: 124 ,size: 0.20, name: "124 "},
{id: 125 ,size: 0.20, name: "125 "},
{id: 126 ,size: 0.20, name: "126 "},
{id: 127 ,size: 0.20, name: "127 "},
{id: 128 ,size: 0.20, name: "128 "},
{id: 129 ,size: 0.20, name: "129 "},
{id: 130 ,size: 0.20, name: "130 "},
{id: 131 ,size: 0.20, name: "131 "},
{id: 132 ,size: 0.20, name: "132 "},
{id: 133 ,size: 0.20, name: "133 "},
{id: 134 ,size: 0.20, name: "134 "},
{id: 135 ,size: 0.20, name: "135 "},
{id: 136 ,size: 0.20, name: "136 "},
{id: 137 ,size: 0.20, name: "137 "},
{id: 138 ,size: 0.20, name: "138 "},
{id: 139 ,size: 0.20, name: "139 "},
{id: 140 ,size: 0.20, name: "140 "},
{id: 141 ,size: 0.20, name: "141 "},
{id: 142 ,size: 0.20, name: "142 "},
{id: 143 ,size: 0.20, name: "143 "},
{id: 144 ,size: 0.20, name: "144 "},
{id: 145 ,size: 0.20, name: "145 "},
{id: 146 ,size: 0.20, name: "146 "},
{id: 147 ,size: 0.20, name: "147 "},
{id: 148 ,size: 0.20, name: "148 "},
{id: 149 ,size: 0.20, name: "149 "},
{id: 150 ,size: 0.20, name: "150 "},
{id: 151 ,size: 0.20, name: "151 "},
{id: 152 ,size: 0.20, name: "152 "},
{id: 153 ,size: 0.20, name: "153 "},
{id: 154 ,size: 0.20, name: "154 "},
{id: 155 ,size: 0.20, name: "155 "},
{id: 156 ,size: 0.20, name: "156 "},
{id: 157 ,size: 0.20, name: "157 "},
{id: 158 ,size: 0.20, name: "158 "},
{id: 159 ,size: 0.20, name: "159 "},
{id: 160 ,size: 0.20, name: "160 "},
{id: 161 ,size: 0.20, name: "161 "},
{id: 162 ,size: 0.20, name: "162 "},
{id: 163 ,size: 0.20, name: "163 "},
{id: 164 ,size: 0.20, name: "164 "},
{id: 165 ,size: 0.20, name: "165 "},
{id: 166 ,size: 0.20, name: "166 "},
{id: 167 ,size: 0.20, name: "167 "},
{id: 168 ,size: 0.20, name: "168 "},
{id: 169 ,size: 0.20, name: "169 "},
{id: 170 ,size: 0.20, name: "170 "},
{id: 171 ,size: 0.20, name: "171 "},
{id: 172 ,size: 0.20, name: "172 "},
{id: 173 ,size: 0.20, name: "173 "},
{id: 174 ,size: 0.20, name: "174 "},
{id: 175 ,size: 0.20, name: "175 "},
{id: 176 ,size: 0.20, name: "176 "},
{id: 177 ,size: 0.20, name: "177 "},
{id: 178 ,size: 0.20, name: "178 "},
{id: 179 ,size: 0.20, name: "179 "},
{id: 180 ,size: 0.20, name: "180 "},
{id: 181 ,size: 0.20, name: "181 "},
{id: 182 ,size: 0.20, name: "182 "},
{id: 183 ,size: 0.20, name: "183 "},
{id: 184 ,size: 0.20, name: "184 "},
{id: 185 ,size: 0.20, name: "185 "},
{id: 186 ,size: 0.20, name: "186 "},
{id: 187 ,size: 0.20, name: "187 "},
{id: 188 ,size: 0.20, name: "188 "},
{id: 189 ,size: 0.20, name: "189 "},
{id: 190 ,size: 0.20, name: "190 "},
{id: 191 ,size: 0.20, name: "191 "},
{id: 192 ,size: 0.20, name: "192 "},
{id: 193 ,size: 0.20, name: "193 "},
{id: 194 ,size: 0.20, name: "194 "},
{id: 195 ,size: 0.20, name: "195 "},
{id: 196 ,size: 0.20, name: "196 "},
{id: 197 ,size: 0.20, name: "197 "},
{id: 198 ,size: 0.20, name: "198 "},
{id: 199 ,size: 0.20, name: "199 "},
{id: 200 ,size: 0.20, name: "200 "},
{id: 201 ,size: 0.20, name: "201 "},
{id: 202 ,size: 0.20, name: "202 "},
{id: 203 ,size: 0.20, name: "203 "},
{id: 204 ,size: 0.20, name: "204 "},
{id: 205 ,size: 0.20, name: "205 "},
{id: 206 ,size: 0.20, name: "206 "},
{id: 207 ,size: 0.20, name: "207 "},
{id: 208 ,size: 0.20, name: "208 "},
{id: 209 ,size: 0.20, name: "209 "},
{id: 210 ,size: 0.20, name: "210 "},
{id: 211 ,size: 0.20, name: "211 "},
{id: 212 ,size: 0.20, name: "212 "},
{id: 213 ,size: 0.20, name: "213 "},
{id: 214 ,size: 0.20, name: "214 "},
{id: 215 ,size: 0.20, name: "215 "},
{id: 216 ,size: 0.20, name: "216 "},
{id: 217 ,size: 0.20, name: "217 "},

{id: 0 ,size: 0.08, name: "0 "},
{id: 1 ,size: 0.08, name: "1 "},
{id: 2 ,size: 0.08, name: "2 "},
{id: 3 ,size: 0.08, name: "3 "},
{id: 4 ,size: 0.08, name: "4 "},
{id: 5 ,size: 0.08, name: "5 "},
{id: 6 ,size: 0.08, name: "6 "},
{id: 7 ,size: 0.08, name: "7 "},
{id: 8 ,size: 0.08, name: "8 "},
{id: 9 ,size: 0.08, name: "9 "},
{id: 10 ,size: 0.08, name: "10 "},
{id: 11 ,size: 0.08, name: "11 "},
{id: 12 ,size: 0.08, name: "12 "},
{id: 13 ,size: 0.08, name: "13 "},
{id: 14 ,size: 0.08, name: "14 "},
{id: 15 ,size: 0.08, name: "15 "},
{id: 16 ,size: 0.08, name: "16 "},
{id: 17 ,size: 0.08, name: "17 "},
{id: 18 ,size: 0.08, name: "18 "},
{id: 19 ,size: 0.08, name: "19 "},
{id: 20 ,size: 0.08, name: "20 "},
{id: 21 ,size: 0.08, name: "21 "},
{id: 22 ,size: 0.08, name: "22 "},
{id: 23 ,size: 0.08, name: "23 "},
{id: 24 ,size: 0.08, name: "24 "},
{id: 25 ,size: 0.08, name: "25 "},
{id: 26 ,size: 0.08, name: "26 "},
{id: 27 ,size: 0.08, name: "27 "},
{id: 28 ,size: 0.08, name: "28 "},
{id: 29 ,size: 0.08, name: "29 "},
{id: 30 ,size: 0.08, name: "30 "},
{id: 31 ,size: 0.08, name: "31 "},
{id: 32 ,size: 0.08, name: "32 "},
{id: 33 ,size: 0.08, name: "33 "},
{id: 34 ,size: 0.08, name: "34 "},
{id: 35 ,size: 0.08, name: "35 "},
{id: 36 ,size: 0.08, name: "36 "},
{id: 37 ,size: 0.08, name: "37 "},
{id: 38 ,size: 0.08, name: "38 "},
{id: 39 ,size: 0.08, name: "39 "},
{id: 40 ,size: 0.08, name: "40 "},
{id: 41 ,size: 0.08, name: "41 "},
{id: 42 ,size: 0.08, name: "42 "},
{id: 43 ,size: 0.08, name: "43 "},
{id: 44 ,size: 0.08, name: "44 "},
{id: 45 ,size: 0.08, name: "45 "},
{id: 46 ,size: 0.08, name: "46 "},
{id: 47 ,size: 0.08, name: "47 "},
{id: 48 ,size: 0.08, name: "48 "},
{id: 49 ,size: 0.08, name: "49 "},
{id: 50 ,size: 0.08, name: "50 "},
{id: 51 ,size: 0.08, name: "51 "},
{id: 52 ,size: 0.08, name: "52 "},
{id: 53 ,size: 0.08, name: "53 "},
{id: 54 ,size: 0.08, name: "54 "},
{id: 55 ,size: 0.08, name: "55 "},
{id: 56 ,size: 0.08, name: "56 "},
{id: 57 ,size: 0.08, name: "57 "},
{id: 58 ,size: 0.08, name: "58 "},
{id: 59 ,size: 0.08, name: "59 "},
{id: 60 ,size: 0.08, name: "60 "},
{id: 61 ,size: 0.08, name: "61 "},
{id: 62 ,size: 0.08, name: "62 "},
{id: 63 ,size: 0.08, name: "63 "},
{id: 64 ,size: 0.08, name: "64 "},
{id: 65 ,size: 0.08, name: "65 "},
{id: 66 ,size: 0.08, name: "66 "},
{id: 67 ,size: 0.08, name: "67 "},
{id: 68 ,size: 0.08, name: "68 "},
{id: 69 ,size: 0.08, name: "69 "},
{id: 70 ,size: 0.08, name: "70 "},
{id: 71 ,size: 0.08, name: "71 "},
{id: 72 ,size: 0.08, name: "72 "},
{id: 73 ,size: 0.08, name: "73 "},
{id: 74 ,size: 0.08, name: "74 "},
{id: 75 ,size: 0.08, name: "75 "},
{id: 76 ,size: 0.08, name: "76 "},
{id: 77 ,size: 0.08, name: "77 "},
{id: 78 ,size: 0.08, name: "78 "},
{id: 79 ,size: 0.08, name: "79 "},
{id: 80 ,size: 0.08, name: "80 "},
{id: 81 ,size: 0.08, name: "81 "},
{id: 82 ,size: 0.08, name: "82 "},
{id: 83 ,size: 0.08, name: "83 "},
{id: 84 ,size: 0.08, name: "84 "},

  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name:  'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id:  ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
